---
- name: Load group vars
  include_vars:
    dir: "{{ workspace_group_vars_dir }}"
    ignore_unknown_extensions: true
  delegate_to: localhost
  become: false
  run_once: true

- name: Validate API avalability
  uri:
    url: "{{ consul_external_url }}/v1/agent/members"
    headers:
      X-Consul-Token: "{{ root_consul.SecretID }}"
    ca_path: "{{ consul_local_ca_certificate }}"
    client_cert: "{{ consul_local_cert_fullchain }}"
    client_key: "{{ consul_local_cert_private_key }}"
  register: _consul_ping_api
  until: _consul_ping_api.status == 200
  retries: 10
  delay: 10
  delegate_to: localhost
  become: false
  run_once: true

- name: "Copy terraform sources"
  copy:
    src: "{{ __consul_terraform_module }}/"
    dest: "{{ __consul_terraform_module_work_dir }}/"
    mode: "u+rwX,g+rX,o-rX"
  delegate_to: localhost
  become: false
  run_once: true

- name: "COMMON - Do Terraform (can take up to 30 minutes)"
  community.general.terraform:
    project_path: "{{ tf_module_dest }}"
    state: "{{ (tf_action == 'destroy') | ternary('absent', 'present') }}"    # noqa args
    force_init: true
    provider_upgrade: true
    workspace: "{{ workspace }}"
    variables:
      consul_address: "{{ consul_external_url }}"
      datacenter: "{{ workspace }}"
      token: "{{ root_consul.SecretID }}"
      ca_file: "{{ consul_local_ca_certificate }}"
      cert_file: "{{ consul_local_cert_fullchain }}"
      key_file: "{{ consul_local_cert_private_key }}"
  register: tf_result
  delegate_to: localhost
  become: false
  run_once: true

- name: Generate host_vars for public_ns
  copy:
    dest: "{{ workspace_secrets_dir }}/tf_consul_config.yml"
    mode: 0600
    content: |-
        ---
        consul_connect_token_nomad_server: "{{ tf_result.outputs.consul_acl_nomad_server_token.value }}"
        consul_connect_token_nomad_client: "{{ tf_result.outputs.consul_acl_nomad_client_token.value }}"
        consul_prometheus_token: "{{ tf_result.outputs.consul_acl_prometheus_token.value }}"
        consul_telemetry_token: "{{ tf_result.outputs.consul_acl_telemetry_token.value }}"
        consul_promtail_token: "{{ tf_result.outputs.consul_acl_promtail_token.value }}"
        consul_acl_auto_encrypt_token: "{{ tf_result.outputs.consul_acl_client_token.value }}"
        consul_nomad2vault_token: "{{ tf_result.outputs.consul_nomad2vault_token.value }}"
        consul_acl_vault_token: "{{ tf_result.outputs.consul_acl_vault_token.value }}"
  delegate_to: localhost
  become: false
  run_once: true
