---
- name: Prepare
  include_tasks: _prepare.yml
  tags:
    - prepare

- name: Install
  include_tasks: _install.yml
  tags:
    - install

- name: Configure
  include_tasks: _configure.yml
  when: inventory_hostname in groups[consul_server_group_name]
  tags:
    - configure

- name: Make sure consul service is running
  systemd:
    name: consul
    daemon_reload: true
    state: started
    enabled: true
  when: inventory_hostname in groups[consul_server_group_name]

- name: Flush
  meta: flush_handlers

- name: Wait for consul api
  wait_for:
    host: "127.0.0.1"
    port: "{{ consul_api_port }}"
    timeout: 60
  when: inventory_hostname in groups[consul_server_group_name]

- name: Bootstrap acl
  include_tasks: _acl_bootstrap.yml
  when:
    - inventory_hostname in groups[consul_bootstrap_group_name]
    - inventory_hostname == groups[consul_bootstrap_group_name][0]
    - >-
      ansible_local.consul is not defined
      or ansible_local.consul.applied is not defined
      or not ansible_local.consul.applied

- name: Configure Vault instance using terraform
  include_tasks: _tf_configure.yml

- name: Configure consul on Servers
  include_tasks: "{{ role_path }}/tasks/services/_consul_servers.yml"
  when: inventory_hostname in groups[consul_server_group_name]
  tags:
    - consul_servers

- name: Load group vars
  include_vars:
    dir: "{{ workspace_group_vars_dir }}"
    ignore_unknown_extensions: true

- name: Configure
  include_tasks: _configure.yml
  tags:
    - configure

- name: Wait for consul api
  wait_for:
    host: "127.0.0.1"
    port: "{{ consul_api_port }}"
    timeout: 60
  when: (inventory_hostname in groups[consul_client_group_name]) or (inventory_hostname in groups['hashistack_sre'])

- name: Configure consul on Clients
  include_tasks: "{{ role_path }}/tasks/services/_consul_clients.yml"
  when:
    - (inventory_hostname in groups[consul_client_group_name]) or (inventory_hostname in groups['hashistack_sre'])
    - (groups[consul_client_group_name] | intersect(groups['hashistack_sre']) | length) == 0
  tags:
    - consul_clients

- name: Flush before leaving
  meta: flush_handlers
  tags: always
