workspace: hashistack

cluster_config:
  servers: 3 # min 2 max 5
  clients: 2
  vault_servers: 1
  vault_volume_size: 10
  consul_volume_size: 10
  separate_consul_servers: false
  multi_instance_observability: false
  ingress:
    management_domain: management.zsmartex.com
    public_domain: zsmartex.com
  client_volumes:
  - name: "data_vol"
    client_id: 1
    path: /opt/nomad_client_data
    size: 20

cloud_provider_config:
  internal_network_interface_name: enp7s0 #ens10
  sudo_user: root
  sudo_dir: /root
  provider: hetzner
  provider_settings:
    server_location: fsn1
    network_location: eu-central
    load_balancer_location: fsn1
    server_instance_type: cpx11
    client_instance_type: cpx21
    observability_instance_type: cpx11
    load_balancer_type: lb11
    resource_names:
      base_server_name: hashistack
      firewall_name: hs_firewall
      network_name: hs_network
