---
__consul_hashicorp_apt_key: >-
  https://apt.releases.hashicorp.com/gpg
__consul_hashicorp_apt_repository: >-
  deb [arch=amd64] https://apt.releases.hashicorp.com bullseye main

__consul_ssl_cert_group: "ssl-cert"

__consul_tls_ca_certificate_dir: "/usr/local/share/ca-certificates"
__consul_tls_dir: "{{ consul_config_path }}/ssl"

__consul_conf_file: "{{ consul_config_path }}/consul.hcl"

__consul_expected_directories:
  - "{{ consul_data_path }}"
  - "{{ consul_config_path }}"
  - "{{ __consul_tls_dir }}"

__consul_bootstrap_list: >-
  {{
    groups[consul_bootstrap_group_name]
    | map('extract', hostvars, 'private_ip')
    | list
    | unique
  }}

__consul_server_list: >-
  {{
    groups[consul_server_group_name]
    | map('extract', hostvars, 'private_ip')
    | list
    | unique
  }}

__consul_is_bootstrap: >-
  {{
    consul_bootstrap_group_name is defined
    and consul_bootstrap_group_name | length > 0
    and inventory_hostname in groups[consul_bootstrap_group_name]
  }}

__consul_is_server: >-
  {{
    __consul_is_bootstrap
    or consul_server_group_name is defined
    and consul_server_group_name | length > 0
    and inventory_hostname in groups[consul_server_group_name]
  }}

__consul_is_client: "{{ not __consul_is_server }}"

__consul_encrypt_key_local_path: "{{ consul_local_secrets_dir }}/consul.encrypt_key"
__consul_encrypt_key: >-
  {{ lookup('file', __consul_encrypt_key_local_path) }}

__consul_tls_ca_crt: "consul-ca.crt"
__consul_tls_server_crt: "server-fullchain.crt"
__consul_tls_server_key: "server.key"

__consul_terraform_module: >-
  consul_config
__consul_terraform_module_work_dir: >-
  {{ consul_terraform_work_dir }}/{{ __consul_terraform_module }}
