---
- name: Restart consul
  systemd:
    name: consul
    state: restarted
    enabled: true

- name: Update ca trust
  command: >-
    /usr/sbin/update-ca-certificates

- name: Restart sidecarvault
  systemd:
    name: sidecarvault
    state: restarted
    daemon_reload: true
    enabled: true

- name: Reload consul
  systemd:
    name: consul
    state: reloaded
    enabled: true

- name: Restart client2vault
  systemd:
    name: client2vault
    state: restarted
    daemon_reload: true
    enabled: true
