---
- name: Prepare
  debug:
    msg: "Starting role installation phase"
    verbosity: 1

- name: Get envoy binary release
  get_url:
    url: "{{ __envoy_binary_release_url }}"
    dest: /usr/local/bin/envoy
    mode: 0755
