---
galaxy_info:
  role_name: "hcloud"
  author: "Hữu Hà"
  description: >-
    Hashistack HCloud - Infrastructure (coupled to collections playbooks)
  issue_tracker_url: >-
    https://github.com/zsmartex/hashistack/issues
  min_ansible_version: "2.14"
  license: MIT
  platforms:
    - name: Amazon
      versions:
        - Candidate
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - "8"
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - iac

dependencies: []
