---
#
# ```{include} ../../../roles/consul/README.md
# ```
#
# ## Defaults
#
tf_module_name: "consul_config"
tf_action: apply

consul_datacenter_name: "{{ workspace }}"
consul_version: "1.15.0-1"
consul_connect_token: ~
consul_server_group: "consul_server_instances"
consul_client_group: "consul_client_instances"

consul_prometheus_enabled: true
consul_connect_root_pki_path: "connect_root"
consul_connect_intermediate_pki_path: "connect_inter"

consul_vault_address: "https://vault.{{ consul_domain }}:8200"
consul_api_port: "8501"
consul_grpc_port: "8502"
consul_grpc_tls_port: "8503"
consul_address: "https://127.0.0.1:{{ consul_api_port }}"



consul_node_name: "{{ inventory_hostname | regex_replace('_', '-') }}"
consul_domain: "{{ public_domain }}"
consul_node_fqdn: "{{ consul_node_name }}.{{ consul_domain }}"

consul_external_url: https://consul.{{ consul_domain }}


consul_bootstrap_expect: "{{ groups[consul_server_group] | length }}"
consul_advertise_addr: "{{ ansible_default_ipv4.address }}"

consul_use_custom_ca: false
consul_local_ca_cert: "{{ workspace_secrets_dir }}/consul-ca.pem"

consul_acl_default_policy: deny
consul_acl_auto_encrypt_token: ~
consul_ca_certificate_dir: "/usr/local/share/ca-certificates"
consul_ca_certificate: "/etc/ssl/certs/ca-certificates.crt"
consul_local_secrets_dir: "{{ workspace_secrets_dir }}"
consul_node_cert: "{{ consul_local_secrets_dir }}/server.pem"
consul_node_cert_private_key: "{{ consul_local_secrets_dir }}/server-key.pem"
consul_node_cert_fullchain: "{{ consul_local_secrets_dir }}/server-fullchain.pem"

