---
tf_module_name: "consul_config"
tf_action: apply

consul_version: "1.15.0-1"
consul_datacenter_name: "{{ workspace }}"

consul_bootstrap_group_name: consul_bootstrap_instances
consul_server_group_name: consul_server_instances
consul_client_group_name: consul_client_instances

consul_api_port: 8501
consul_grpc_port: 8502
consul_grpc_tls_port: 8503

consul_bind_address: "{{ private_ip }}"

consul_data_path: /opt/consul
consul_config_path: /etc/consul.d

consul_ui_enabled: true

consul_vault_address: "https://{{ hostvars[groups['vault_servers'][0]]['private_ip'] }}:8200"
consul_external_url: "https://{{ hostvars[groups['consul_server_instances'][0]]['public_ip'] }}:{{ consul_api_port }}"

consul_acl_enabled: true
consul_acl_default_policy: deny
consul_acl_token_persistence_enabled: true

consul_prometheus_enabled: true

consul_tls_enabled: true
consul_local_secrets_dir: "{{ workspace_secrets_dir }}"
consul_local_ca_certificate: "{{ consul_local_secrets_dir }}/certificate-authority.pem"
consul_local_cert_fullchain: "{{ consul_local_secrets_dir }}/server-fullchain.pem"
consul_local_cert_private_key: "{{ consul_local_secrets_dir }}/server-key.pem"

consul_terraform_work_dir: "{{ workspace_tf_modules_dir }}"
