---
__role_vars_precedence:
  - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}_{{ ansible_architecture | lower }}.yml"
  - "{{ ansible_distribution | lower }}_{{ ansible_architecture | lower }}.yml"
  - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_os_family | lower }}.yml"

__role_tasks_precedence:
  - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}_{{ ansible_architecture | lower }}/main.yml"
  - "{{ ansible_distribution | lower }}_{{ ansible_architecture | lower }}/main.yml"
  - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}/main.yml"
  - "{{ ansible_distribution | lower }}/main.yml"

__vault_api_addr: >-
  {{ vault_api_protocol }}://{{ vault_internal_ip }}:{{ vault_api_port }}

__vault_cluster_addr: >-
  {{ vault_cluster_protocol }}://{{ vault_cluster_address }}:{{ vault_cluster_port }}

__vault_api:
  status: "{{ __vault_api_addr }}/v1/sys/seal-status"
  init: "{{ __vault_api_addr }}/v1/sys/init"
  unseal: "{{ __vault_api_addr }}/v1/sys/unseal"
  lookup_self: "{{ __vault_api_addr }}/v1/auth/token/lookup-self"

__vault_tls_dir: "/etc/ssl/private"

__vault_ssl_cert_group: "ssl-cert"

__vault_conf_dir: "/etc/vault.d"
__vault_data_dir: "/opt/vault/data"
__vault_expected_directories:
  - "{{ __vault_data_dir }}"
  - "{{ __vault_conf_dir }}"

__vault_conf_file: "{{ __vault_conf_dir }}/vault.hcl"

__vault_self_private_key: "{{ __vault_tls_dir }}/server-key.pem"
__vault_self_certificate: "{{ __vault_tls_dir }}/server-fullchain.pem"
__vault_ca_certificate_dir: "/usr/local/share/ca-certificates"
__vault_ca_certificate: "{{ __vault_ca_certificate_dir }}/vault-ca.pem"

__vault_is_first_server: >-
  {{ inventory_hostname == groups[vault_servers_group][0] }}

__vault_server_partners: >-
  {{
    groups[vault_servers_group]
    | difference([inventory_hostname])
    | map('regex_replace', '_', '-')
    | map('regex_replace', '$', '.' + vault_domain)
  }}

__vault_terraform_module: >-
  vault_config

__vault_terraform_module_work_dir: >-
  {{ vault_terraform_work_dir }}/{{ __vault_terraform_module }}
