---
- name: Init first node
  include_tasks: "_inplace_init.yml"
  when: __vault_is_first_server

- name: Unseal first node
  include_tasks: "_inplace_unseal.yml"
  vars:
    vault_unseal_target: "{{ [groups[vault_servers_group][0]] }}"

- name: Get vault status
  uri:
    url: "{{ __vault_api.status }}"
    return_content: true
    ca_path: "{{ __vault_ca_certificate }}"
    client_cert: "{{ __vault_self_certificate }}"
    client_key: "{{ __vault_self_private_key }}"
  register: _current_vault_status
  when: __vault_is_first_server
  retries: 10
  delay: 10
  until:
    - _current_vault_status.status == 200
    - not _current_vault_status.json.sealed

- name: Handling first init variable propagation
  set_fact:
    vault_init_content: "{{ hostvars[groups[vault_servers_group][0]].vault_init_content }}"
  when:
    - inventory_hostname in groups[vault_servers_group][1:]
    - vault_init_content is not defined

- name: Assert unseal keys content
  assert:
    that:
      - vault_init_content is defined
  no_log: true

- name: Unseal other nodes
  include_tasks: "_inplace_unseal.yml"
  vars:
    vault_unseal_target: "{{ groups[vault_servers_group][1:] }}"
