---
- name: Reload workspace vars
  include_vars:
    dir: "{{ workspace_group_vars_dir }}"
    ignore_unknown_extensions: true

- name: Wait for load balancer warm up
  uri:
    ca_path: "{{ vault_local_ca_cert }}"
    url: "{{ vault_api_protocol }}://{{ vault_external_ip }}:{{ vault_api_port }}/v1/auth/token/lookup-self"
    headers:
      X-Vault-Token: "{{ vault_init_content.root_token }}"
  register: _vault_ping_api
  until: _vault_ping_api.status == 200
  retries: 2
  delay: 10
  delegate_to: localhost
  become: false
  run_once: true

- name: Copy terraform sources    # noqa risky-file-permissions
  copy:
    src: "{{ __vault_terraform_module }}/"
    dest: "{{ __vault_terraform_module_work_dir }}/"
  delegate_to: localhost
  become: false
  run_once: true

- name: "Do Terraform"
  community.general.terraform:
    project_path: "{{ __vault_terraform_module_work_dir }}"
    state: "present"    # noqa args
    force_init: true
    provider_upgrade: true
    workspace: "{{ vault_cluster_name }}"
    variables:
      vault_address: >-
        {{ vault_api_protocol }}://{{ vault_external_ip }}:{{ vault_api_port }}
      vault_ca_cert_file: >-
        {{ vault_use_custom_ca | ternary(vault_node_ca_cert, '') | default(omit, true) }}
      nomad_allowed_vault_policies: >-
        {{ nomad_allowed_vault_policies | default([], true) | to_json }}
  environment:
    VAULT_ADDR: "{{ vault_api_protocol }}://{{ vault_external_ip }}:{{ vault_api_port }}"
    VAULT_TOKEN: "{{ vault_init_content.root_token }}"
  register: tf_result
  delegate_to: localhost
  become: false
  run_once: true

- name: Cook variables
  set_fact:
    _tf_vault_outputs:
      consul_connect_token: "{{ tf_result.outputs.consul_connect_client_token.value }}"
      consul_connect_root_pki_path: "{{ tf_result.outputs.root_pki_path.value }}"
      consul_connect_intermediate_pki_path: "{{ tf_result.outputs.inter_pki_path.value }}"
      pki_root_certificate_b64: "{{ tf_result.outputs.root_certificate.value | b64encode }}"
      vault_telemetry_token: "{{ tf_result.outputs.telemetry_token.value }}"
      nomad_vault_token: "{{ tf_result.outputs.nomad_vault_token.value }}"
  delegate_to: localhost
  become: false
  run_once: true

- name: Generate host_vars for public_ns
  copy:
    dest: "{{ vault_local_secret_dir }}/tf_vault_config.yml"
    content: |-
      ---
      {{ _tf_vault_outputs | to_nice_yaml(indent=2) }}
    mode: 0600
  delegate_to: localhost
  become: false
  run_once: true
