---
- name: Stage 1 - Create certificate
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Create certificate
      include_role:
        name: certificate
      vars:
        consul_domain: consul
        public_domain: "{{ cluster_config.ingress.public_domain }}"
        management_domain: "{{ cluster_config.ingress.management_domain }}"
        certificate_bares: ["server", "client"]
        subject_alt_name: >-
          {{
            groups['hashistack']
            | map('extract', hostvars, 'private_ip')
            | map('regex_replace', '^(.*)^', 'IP:')
            | list
            | unique
            +
            groups['hashistack']
            | map('extract', hostvars, 'public_ip')
            | map('regex_replace', '^(.*)^', 'IP:')
            | list
            | unique
          }}
