---
- name: Stage 2 - Copy certificate to consul servers
  hosts: nomad_servers,client_servers
  become: true
  gather_facts: true
  pre_tasks:
    - name: Add nomad group
      group:
        name: "nomad"
    - name: Add nomad user
      user:
        name: "nomad"
        group: "nomad"
    - name: Creates data dir
      file:
        path: '{{ item["mount_path"] }}/{{ item["name"] }}'
        state: directory
        owner: "{{ item['owner'] }}"
        group: "{{ item['group'] }}"
        mode: 0755
      loop: "{{ volumes }}"
    - name: Links data dir
      file:
        src: '{{ item["mount_path"] }}/{{ item["name"] }}'
        dest: "{{ item['path'] }}"
        state: link
        owner: "{{ item['owner'] }}"
        group: "{{ item['group'] }}"
      loop: "{{ volumes }}"
  roles:
    - role: rtnp.galaxie_clans.container
    - role: nomad
