---
#
# ```{include} ../../../roles/vault/README.md
# ```
#
# ## Defaults
#
# * Domain under which
vault_cluster_name: "{{ workspace }}"
#
#
# * Path on the ansible controller
vault_local_secret_dir: "{{ workspace_secrets_dir }}"

vault_node_name: "{{ inventory_hostname | regex_replace('_', '-') }}"

vault_version: "1.12.3-1"

vault_servers_group: "vault_servers"

vault_api_protocol: "https"
vault_api_port: "8200"
vault_api_address: "{{ vault_internal_ip }}"
vault_api_listener: "{{ vault_api_address }}:{{ vault_api_port }}"

vault_cluster_protocol: "https"
vault_cluster_address: "{{ vault_internal_ip }}"
vault_cluster_port: "8201"
vault_cluster_listener: "{{ vault_internal_ip }}:{{ vault_cluster_port }}"
#
# ### Unseal
#
vault_unseal_method: "in-place"
vault_unseal_key_shares: 5
vault_unseal_key_threshold: 3
#

#
# ### Certificates
#
vault_local_unseal_file: "{{ vault_local_secret_dir }}/root_vault.yml"
vault_local_ca_cert: "{{ vault_local_secret_dir }}/certificate-authority.crt"
vault_local_cert: "{{ vault_local_secret_dir }}/server.crt"
vault_local_cert_private_key: "{{ vault_local_secret_dir }}/server.key"
vault_local_cert_fullchain: "{{ vault_local_secret_dir }}/server-fullchain.crt"
#

#
# ### Teraform
#
vault_terraform_work_dir: "{{ workspace_tf_modules_dir }}"
#
